#ifndef EVENTID_H
#define EVENTID_H

enum EVENTS
{
	MAINFRAMEEVENTSMIN = wxID_HIGHEST + 1,
	ID_GO,
	ID_STOP,
	ID_PAINT,
	ID_EYEPANELPAINT_TIMER,
	ID_NSSOCKET_EVENT,
	ID_SPSOCKET_EVENT,
	ID_TIMER_NSCONNECTIONTIMEOUT,
	ID_TIMER_NSDISCONNECTIONTIMEOUT,
	ID_TIMER_SPCONNECTIONTIMEOUT,
	ID_TIMER_SPDISCONNECTIONTIMEOUT,
	ID_TIMER_PAINT,
	ID_RETINA_UPDATE,
	ID_MOTOR_FORCE_UPDATE,
	ID_TORQUE_FORCE_UPDATE,
	ID_OBJECT_PROCESS_THREAD_DONE,
	ID_PROCESSPACKET,
	EVENTSMAX
};



#endif