

tb_spi_control: spi_control
	vcom -93 tb_pna_spi_control.vhd

tb_spi_if: spi_if
	vcom -93 tb_pna_spi_if.vhd

spi_control:
	vcom -93 ../src/pna_spi_control.vhd
spi_if:
	vcom -93 ../src/pna_spi_if.vhd