#ifndef EVENTID_H
#define EVENTID_H

enum EVENTS
{
	MAINFRAMEEVENTSMIN = wxID_HIGHEST + 1,
	ID_VIEWERFRAME,
	ID_GLPANEL,
	ID_CONNECT_PANEL,
	ID_SIDEPANEL,
	ID_MAINPANEL,
	ID_NOTEBOOK,
	ID_GO,
	ID_STOP,
	ID_SOCKET_EVENT,
	ID_TIMER_CONNECTIONTIMEOUT,
	ID_TIMER_DISCONNECTIONTIMEOUT,
	ID_VIEWERFRAME_REDRAW_TIMER,
	ID_VIEWERFRAME_FORCE_TIMER,
	ID_FORCEBUTTON,
	ID_ADDINANIMATE,
	ID_OBJECTSELECT,
	ID_VIEWSELECT,
	ID_PROCESSPACKET,
	EVENTSMAX
};

#endif