#ifndef EVENTID_H
#define EVENTID_H
enum EVENTS
{
	MAINFRAMEEVENTSMIN = wxID_HIGHEST + 1,
	ID_TESTDBSETTINGS,
	ID_INITIALIZEDB,
	ID_SERVERSTART,
	ID_SERVERRESTART,
	ID_SERVERSTOP,
	ID_SERVERSOCKET,
	ID_PHYSTHREADEVENT,
	ID_PHYSICSSENDBULKEVENT,
	ID_PROCESSPACKETEVENT,
	ID_FORWARDPACKETEVENT,
	ID_FORWARDPACKETTOALLCLIENTSEVENT,
	EVENTSMAX
};
#endif